### ISSUE TITLE
[Feature Request] Support Obsidian Mobile

### ISSUE THREAD

**Issue by FelipeRearden** [lijyze/obsidian-state-switcher#1]
Hello @lijyze !!!!

Fantastic idea 💙

I really need a plugin to automate my YAML/frontmatter metadata since all of my notes has metadata. Thank you for your work !!!

I am just starting to use today and I will bring more FR for you to take a look... 👀 👀 👀 

### My FR

Since I use Obsidian on iPad using keyboard and mouse, my first FR is to bring this amazing plugin to Obsidian Mobile.

Would be amazing to have the same workflow that I have on desktop with my iPad :)

---

Thanks for reading this !

Have a great day ☀️

**Comment by lijyze** [comment]
Think for you like, I already make it usable on mobile device. Mobile device is only used for reading, so I simply make it unmobiable. But, consider about the code, I think it will play well with mobile device.

If you want to make any plugin mobilable, you can change `isDesktopOnly` property to `true` in `manifest.json`, but you should know, this may cause conflict. if conflict occur, you should change `isDesktopOnly` back to `false`.

**Comment by FelipeRearden** [comment]
Hello @lijyze !!!!

Forgive for my late reply :)

> Think for you like, I already make it usable on mobile device. Mobile device is only used for reading, so I simply make it unmobiable. 

Thanks you very much for making available for installation on mobile  !!!!!!

>  If you want to make any plugin mobilable, you can change isDesktopOnly property to true in manifest.json, but you should know, this may cause conflict. if conflict occur, you should change isDesktopOnly back to false.

Thank very much for this comment about `manifest.json` 😃 😃 😃

---

> But, consider about the code, I think it will play well with mobile device.

The plugin is successful installed but I cant enable on Mobile :(

See the image below …
![D3B45239-B7CD-4C18-B036-40E6F508C4CB](https://user-images.githubusercontent.com/85180696/171700381-39129abd-17fa-403d-b538-24a372c521a3.png)

I already face this issue with two other plugins and if you don’t mind I will share some information to help in this issue :)

Our Obsidian friend [Quorafind](https://github.com/Quorafind) had this issue with the plugin [Obsidian Memos](https://github.com/Quorafind) and the issue was that …

📱 iOS does not support `lookbehind regex`. 

This is the comment about this -> https://github.com/jglev/obsidian-carry-forward/issues/3#issuecomment-1008922788

--- 

I hope you find a way to run this amazing plugin on iOS 🙏

Thanks for reading this and have a great day 🌞!!!!!

**Comment by lijyze** [comment]
Thanks for your hint, it saved much time.
Update plugin to version 1.0.3, it will works well.

**Comment by FelipeRearden** [comment]
> Thanks for your hint, it saved much time.

I'm very very happy to help 😀
 
> Update plugin to version 1.0.3, it will works well.

Working prefect on version 1.0.3 on Obsidian Mobile (iPadOS 15.4) 1.2.0


Thank you very much @lijyze !!!!!!
