### ISSUE TITLE
Enhancement: Allow choosing tags by a (potentially fuzzy) tag search based on already-in-vault-existing tags

### ISSUE THREAD

**Issue by Gewerd-Strauss** [lijyze/obsidian-state-switcher#10]
Hello,

the second suggestion I have would be to allow a (preferably fuzzy?) search over already existing tags to be entered as values when updating. Similarly, this would mean implementing an edit-field and then querying all tags of the vault; allowing the user to search for and select tags they want to implement. When selected, they are added. Added tags can be removed the same way they are done right now by simply deselecting them. Overall, this would free up configuration overhead and allow the plugin to be used moreso as a  quick yaml modifier, instaed of constantly having to update the config as well. Right now, we either get unreasonably large checkbox lists which are unorganised and hard to oversee when taken to the extreme (mild example cf. Image 1), or we end up with a manager containing only very few and specific state types - very general stuff like the default "waiting-ongoing-completed". For status fields that is probably fine, but not really for `key-array`-formatted fields, which can have many entries.

Image 1: ![grafik](https://user-images.githubusercontent.com/80548781/189069924-a165c5eb-0cd6-48d0-8256-96550f6dd065.png)

Thank you,
Sincerely,
~Gw

**Comment by lijyze** [comment]
If you want to a tag that doesn't exist in config, directly edit plain yaml frontmatter seems more convenient.
You can try to use `key-array insert` functionality to search a existing tag and add it to yaml front-matter
