### ISSUE TITLE
[Idea] Working with Obsidian YAML tags

### ISSUE THREAD

**Issue by FelipeRearden** [lijyze/obsidian-state-switcher#2]
Hello again @lijyze !!!!!!!!

I wanna share with you one idea to make easier to use this spectacular plugin with the `tags` metadata that we have in YAML/frontmatter 

Since this idea have more than one FR, I divided each idea into one header for make easy to explain to you.
- I am gonna use a simple example to make things easier for me to explain.

⚠️ English is not my native language. Forgive for my mistakes and let me know if something is not clear. 

## Environment 

⚙️ These are my maps is the plugins settings:

Map 1️⃣ 
```
/* Map */
tags: 

/* Key-values */
Fruits/Apple
Fruits/Grape
Fruits/Orange
```

Map 2️⃣ 
```
/* Map */
tags: 

/* Key-values */
Veggies/Zucchini
Veggies/Carrot
Veggies/Potato
```

📝 This is the YAML of a Note

```
---
tags: [Fruits/Apple,Veggies/Carrot]
---
```

## My Workflow

Would be amazing to use this plugin to **edit** the `tags` YAML  

The main idea is to be able to **keep** items in the `tags` when the user is using the plugin 
- today the plugin replace the content of the YAML with the key-value select in the modal

Let me talk more about this is on each FR :)

### FR 01 -> Support for ALIAS on map

Be able to define an **alias** for each map when selecting items in the modal.

Following my example, we would have something like this  

Map 1️⃣
```
map = tags:
alias = Fruits
```

Map 2️⃣
```
map = tags:
alias = Veggies
```

I could have different modal items `Fruits` and `Veggies` to be applied to the same map `tags`

### FR 02 -> Support for tags syntax

The Obsidian YAML/frontmatter support 4 types of syntax: 

[More info here ](https://help.obsidian.md/Advanced+topics/YAML+front+matter)

```
---
key: value
key2: value2
key3: [one, two, three]
key4:
- four
- five
- six
---
```

Would be amazing if this plugin could support types `3` and `4`

My specific case in type `3` 🙏

### FR 03 -> Modify Key-value instead of Replace

I'm gonna explain this with an example :)

This is my YAML

```
---
tags: [Fruits/Apple,Veggies/Carrot,Drink/Water]
status: [Ready]
---
```

I want to **only modify** the map `tags: Fruits/Apple` to the key-value `Fruits/Orange` without changing the other values of the map `tags:`

- Step 1: Open Modal
- Step 2: Select `Fruits` (alias of `tags: Fruits/Apple,Fruits/Orange,Fruits/Grape`)
- Step 3: Select `Fruits/Orange`

The expected result is this :

```
---
tags: [Fruits/Orange,Veggies/Carrot,Drink/Water]
status: [Ready]
---
```

---
Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by lijyze** [comment]
At the very beginning, I want a plugin to take care only `state` field for me. I made it a little further when I implement this plugin - it take care key-value structure.

I have considered in these days to make it able to manage structures more then key-value structure, such as key-array,(which is the feature you are requiring, if I haven't misunderstood) and key-object. I think it won't long, just be patient.

**Comment by FelipeRearden** [comment]
> At the very beginning, I want a plugin to take care only `state` field for me. I made it a little further when I implement this plugin - it take care key-value structure.

100% understood 😀

> I have considered in these days to make it able to manage structures more then key-value structure, such as key-array,(which is the feature you are requiring, if I haven't misunderstood) and key-object. 

I have been using Obsidian for almost 3 years I early realize that Metadata/YAML is very important piece of the puzzle to manage and search and connect content inside Obsidian

We have at least 5 beta/recent plugins that deviates from Dataview plugin that are used to create tables from notes using YAML metadata!

That's why I am so excited about your plugin because I think you create the easiest and fastest way to manage metadata :
- a database with maps and key-values that can be selected form a modal :)

> I think it won't long, just be patient.

Thank you very much for considering my Idea/FR for future versions :)

100% Okay ! I will wait for your feedback 💙

---

Let's keep talking !

Thank you very much and have a great day!!!! 🌞

**Comment by lijyze** [comment]
New version released.
Key-array structure has been supported.

**Comment by FelipeRearden** [comment]
> New version released.
> 
> Key-array structure has been supported.

Working on version 1.0.2 Obsidian 0.14.6 

Thank you very much for this new feature !!!!
