### ISSUE TITLE
[Feature Request] Back Button inside de Key-Value Modal

### ISSUE THREAD

**Issue by FelipeRearden** [lijyze/obsidian-state-switcher#4]
Hello @lijyze !!!!

Would be amazing to have a `Back <-` in the last line of the Key-Value modal .

Sometimes I made a mistake to select the wrong map and I have to type ESC and my hotkey to open the Modal again to select the right map.

This image is from the QuickAdd plugin that has a back button inside a Modal

![C07B63FD-89ED-4D5A-B5D0-DCC9D962BF32](https://user-images.githubusercontent.com/85180696/172060180-9fff0edd-629a-4382-9772-5a3a488fe819.jpeg)

---

Thanks reading this and have a great day!!!!

**Comment by lijyze** [comment]
Finished

**Comment by FelipeRearden** [comment]
> Finished

Working on version 1.0.2 Obsidian 0.14.6 :)

Thank you !
