### ISSUE TITLE
[Feature Request] CRTL/CMD+ENTER to Keep the Map Modal Active

### ISSUE THREAD

**Issue by FelipeRearden** [lijyze/obsidian-state-switcher#5]
Hello @lijyze !!!

MY FR is about a new behavior to the `CRTL/CMD+ENTER` behavior when I’m selecting a key-value from the modal.
- After hitting `CRTL/CMD+ENTER` the key-value is inserted in the Active Note AND the Modal is not closed and come back to the State Modal.

Let me use an exemple to show this FR:

1️⃣ This is my 2 Maps 

![40141D5B-F39E-400D-88CC-81F24A59D7D6](https://user-images.githubusercontent.com/85180696/172060433-00ac48d4-3305-44e0-95c2-1b773fb136ba.jpeg)

2️⃣ For a Note that I’m working I want to add two metadatas : Priority and Status

### MY FR

ℹ️ This is my idea 

Step 01: Open Switch State Modal - `Status` | `Priority` 

Step 02: Choose `Status` by hitting `ENTER` 

Step 03: Choose `Undone` by hitting `CRTL/CMD+ENTER`

Step 04: **Automatic go to ->** Open Switch State Modal - `Status` | `Priority` 

Step 05: Choose `Priority` by hitting `ENTER` 

Step 05: Choose `Low` by hitting `ENTER` 

Step 06: Modal is closed and I’m back on the active note.

---

Let me know if you need more information :)

Have a great day!!!!

**Comment by lijyze** [comment]
The build-in suggester modal seems can't trigger select action by press `MODIFIER` + `key`, unless you press `MODIFIER` and select item by mouse.

I do think there should by a way to handle multiple field in one time, but I don't think achieve this with suggester modal is a good solution. But there will be a solution, it will have a low priority then support for key-array structure.

**Comment by FelipeRearden** [comment]
> The build-in suggester modal seems can't trigger select action by press `MODIFIER` + `key`, unless you press `MODIFIER` and select item by mouse.
> 
> 
> 
> I do think there should by a way to handle multiple field in one time, but I don't think achieve this with suggester modal is a good solution. But there will be a solution, it will have a low priority then support for key-array structure.

100% understood 👍 

Thank very much for the feedback !

**Comment by lijyze** [comment]
Hi, sorry for having been so long.
functionality `bulk update` has been release, you can find it in command palette.
Hope you like this interaction method.

**Comment by FelipeRearden** [comment]
> Hi, sorry for having been so long.

No problem. I hope everting is okay 😀

> functionality `bulk update` has been release, you can find it in command palette.
> Hope you like this interaction method.

Wooooooowwww !!!! AMAZING this much better than I could image !!!!

Thank you very much its working perfect on Obsidian version `0.14.15`
- I am gonna start to implement this feature in my workflow and I get back to you with more FR and Ideas 

From my opinion, this Issue is closed 🔒

---

⚠️ **There is one point that I want to check with you before creating a new FR**

Obsidian supports two methods for dealing with `key-arrays` items: 
- Link: https://help.obsidian.md/Advanced+topics/YAML+front+matter

1️⃣ **Method**
```
---
key4:
- four
- five
- six
---
```
2️⃣ **Method**

```
---
key3: [one, two, three]
---
```

My whole vault is based on 2️⃣ **Method** for the variable `tags`

📸 One example with a few values
![1F848EDD-D2F2-44F2-9C4F-D60C39F43004](https://user-images.githubusercontent.com/85180696/175548117-0627fd57-7676-4315-9e75-90d7191744a1.jpeg)

This way I wanna check with you if you could add support for 2️⃣ **Method** 🙏🙏🙏🙏🙏
- Maybe a checkbox in the YAML Manager Settings (I loved the new name 😆 )

Let me know what you think :)

Have a great and thanks again for this new feature!!!!

**Comment by lijyze** [comment]
For me, I do want user can determine the shape of structure they want,
But for now, everything is handle by build-in method, which means method 1 is the result of the function. 
I'm not sure if I can determine the shape of key-array structure in an elegant way, but I'll explore it.
I'll let you know if I get any clue.

**Comment by FelipeRearden** [comment]
> For now, everything is handle by build-in method, which means method 1 is the result of the function. 

 
> I'm not sure if I can determine the shape of key-array structure in an elegant way, but I'll explore it.

I really appreciate you trying !!! I hope you find a solution 🙏🙏🙏

the `tags` YAML is my big struggle to update. For Books notes, I would have 10/30 lines of `key-array` which could make the YAML very big using method 1 :(
 
Just an example:
![image](https://user-images.githubusercontent.com/85180696/175554710-8fe9bc1a-dca1-4c2b-a2cb-0eda7b48fe2e.jpeg)

> I'll let you know if I get any clue.

Thank you very much for caring 💙

**Comment by lijyze** [comment]
Hey, please try v1.3.0, you can config how should you key-array field display with this version

**Comment by FelipeRearden** [comment]
> Hey, please try v1.3.0, you can config how should you key-array field display with this version

You did it !!!!!!!! 🎉🎉🎉🎉🎉🎉🎉🎉🎉

Thank you very much, you have no idea how happy I am right now :)

I did some tests before writing this reply to you and it's working absolutely perfect !!! (even on iPadOS/Mobile)
- For me this issue is closed 

Thanks again @lijyze for creating this amazing tool !!!!!!!!!!!!!!!!!! 🙏

**Comment by lijyze** [comment]
Thank you, I'm kinda new open source developer, this experience means a lot to me.

**Comment by FelipeRearden** [comment]
> Thank you, I'm kinda new open source developer, this experience means a lot to me.

You are doing an amazing job !!!!!!!!!!!!!!!!!!!!!!
