### ISSUE TITLE
Works on root files only

### ISSUE THREAD

**Issue by chadchudson** [lijyze/obsidian-state-switcher#6]
I installed your plug-in and it worked beautifully. I migrated my vault to use Obsidian sync vs iCloud. Now SS only works on root files - works perfectly on them, but not files in a folder. I have uninstalled/reinstalled the plug-in. I have tried creating new files in folders to test, etc. Any thoughts? I love the plug-in and quickly got addicted to it!

**Comment by chadchudson** [comment]
More info - in files in the root, it will go through the entire process - state key-value update -> state -> select option -> update YAML

In files in a folder, it pulls up state key-value update -> state (when clicking on state, it simply disappears without doing anything)

**Comment by lijyze** [comment]
I'm sorry for that, it is a low-level mistake.
Please update to latest version, plugin should work correctly

**Comment by chadchudson** [comment]
All good! It works perfectly now! Thank you, great job on the plug-in!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
