### ISSUE TITLE
[Feature Request] Bulk Update Modal : Support for Aliases

### ISSUE THREAD

**Issue by FelipeRearden** [lijyze/obsidian-state-switcher#7]
Hello @lijyze !!!

Just one simple FR that I think could be very good for the new Bulk Modal

What about support for Aliases in the Bulk Modal ?

Many plugins create strange names for the content applied in the YAML 
- https://github.com/bwydoogh/obsidian-force-view-mode-of-note#obsidian-force-note-view-mode
- https://github.com/onlyafly/number-headings-obsidian
- https://github.com/mo-seph/obsidian-note-from-template#from-template-yaml-tags

![659BDAFC-A464-4037-BDC1-B733BFB43CD6](https://user-images.githubusercontent.com/85180696/175559614-b15d36bb-cf54-4eb4-86f6-64ee5613057d.jpeg)

![4AC786F1-503B-4219-A614-88950BE03538](https://user-images.githubusercontent.com/85180696/175559621-216087c4-4459-4d92-afe9-76127a0fb3a8.jpeg)

Be able to define an alias in the Settings would make the Modal even more beautiful :) 

---

Thanks for reading this !!!!!!

**Comment by lijyze** [comment]
I don't think alias is necessary if it only use to display in bulk update modal, besides alias can't fix the problem - you shouldn't also make alias too long.

I have released an optimization. I make the width of the container of the key flexible. This should make it display well.
The scope may not suit for anybody, if you want customize it, you can add following snippet to a css file in `vault/.obsidian/snippets`

```css
.yaml_manager-bulk_update_modal .field_key_container {
  min-width: 120px; 
  max-width: 40%;
}
```

**Comment by FelipeRearden** [comment]
> I don't think alias is necessary if it only use to display in bulk update modal, besides alias can't fix the problem - you shouldn't also make alias too long.

100% understood

> I have released an optimization. I make the width of the container of the key flexible. This should make it display well.

Thanks for the optimization.
> 
> The scope may not suit for anybody, if you want customize it, you can add following snippet to a css file in `vault/.obsidian/snippets`


And thanks for the CSS snippet.
