### ISSUE TITLE
Enhancement: Allow custom choices to be entered in modal popup

### ISSUE THREAD

**Issue by Gewerd-Strauss** [lijyze/obsidian-state-switcher#9]
Hello,

While the addon can be useful, I find it is hindered drastically by relying on preset choices only. 
![grafik](https://user-images.githubusercontent.com/80548781/189066092-a13760a5-24bb-4553-ad24-466de9f3b39a.png)
Above, you can see how both formats ("key-value" and "key-array") are formatted when used. 

I would suggest that for each field (`state`,`tags` & `types`) you get the choices you've preset (`waiting`, `ongoing`, `completed`/ `Internship/Candidate`, `people/`, and so on), but also allow an textinput field to directly enter custom tags to be entered _without_ having to configure them first. This would be a massive help because otherwhise we end up having to create thirty, fourty tags, cluttering the input. Additionally, this would make nested tags (e.g. `#people/`) actually usable, because we could add whatever nesting we have. I use nested tags a lot to keep track of broader subjects, and including them all could easily drive me into the hundreds - at which point this manager will become rather useless.
![grafik](https://user-images.githubusercontent.com/80548781/189068601-a991e02f-00ee-42fd-ba7f-e0cd9202000b.png)

I hope I could explain the idea and my reasoning for it properly. I'll happily answer any questions if I failed to do so.

Thank you.
Sincerely,
~Gw

**Comment by lijyze** [comment]
About text Input, this plugin's aim is to avoid input mistake by removing input operation. Adding a text input seems bring input operation back. I do think this would make things more convenient, but I'm not sure if it's a good idea to add this functionality.

As for the nested tags, I get a little confused. I don't know how you want to config it and how you wish it display, could you please explain that more clearly?
